spring:
  rabbitmq:
    host: 192.168.204.127
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher